"""initial domain schema

Revision ID: 2f9fa12c5504
Revises:
Create Date: 2026-08-19 05:49:37.696361
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "2f9fa12c5504"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cases",
        sa.Column(
            "status",
            sa.Enum(
                "intake", "active", "completed", "abandoned", name="casestatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cases_status"), "cases", ["status"], unique=False)
    op.create_table(
        "household_profiles",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("location_city", sa.String(length=100), nullable=True),
        sa.Column("location_state", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_household_profiles_case_id"), "household_profiles", ["case_id"], unique=True
    )
    op.create_table(
        "life_events",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_life_events_case_id"), "life_events", ["case_id"], unique=True)
    op.create_table(
        "tasks",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_id", sa.String(length=100), nullable=False),
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "ready",
                "in_progress",
                "awaiting_approval",
                "submitted",
                "completed",
                "failed",
                "blocked",
                name="taskstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("input_data", sa.JSON(), nullable=False),
        sa.Column("output_data", sa.JSON(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_tasks_case_id_status", "tasks", ["case_id", "status"], unique=False)
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_table(
        "approval_requests",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("action_description", sa.String(length=500), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", name="approvalstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_approval_requests_status"), "approval_requests", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_approval_requests_task_id"), "approval_requests", ["task_id"], unique=False
    )
    op.create_table(
        "audit_entries",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_entries_case_id"), "audit_entries", ["case_id"], unique=False)
    op.create_index(
        op.f("ix_audit_entries_event_type"), "audit_entries", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_audit_entries_task_id"), "audit_entries", ["task_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("produced_by_task_id", sa.Uuid(), nullable=True),
        sa.Column("document_type", sa.String(length=100), nullable=False),
        sa.Column("owner_name", sa.String(length=200), nullable=False),
        sa.Column("issuer", sa.String(length=200), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "verification_status",
            sa.Enum(
                "pending", "verified", "rejected", name="verificationstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("extracted_fields", sa.JSON(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["produced_by_task_id"], ["tasks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_case_id"), "documents", ["case_id"], unique=False)
    op.create_index(
        op.f("ix_documents_document_type"), "documents", ["document_type"], unique=False
    )
    op.create_index(
        op.f("ix_documents_produced_by_task_id"), "documents", ["produced_by_task_id"], unique=False
    )
    op.create_index(
        op.f("ix_documents_verification_status"), "documents", ["verification_status"], unique=False
    )
    op.create_table(
        "external_applications",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("adapter_type", sa.String(length=100), nullable=False),
        sa.Column("external_reference_id", sa.String(length=200), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "prepared",
                "submitted",
                "processing",
                "approved",
                "rejected",
                "error",
                name="externalapplicationstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("request_payload", sa.JSON(), nullable=False),
        sa.Column("response_payload", sa.JSON(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_external_applications_external_reference_id"),
        "external_applications",
        ["external_reference_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_applications_status"), "external_applications", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_external_applications_task_id"), "external_applications", ["task_id"], unique=False
    )
    op.create_table(
        "people",
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("relationship", sa.String(length=100), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=True),
        sa.Column("is_deceased", sa.Boolean(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["household_id"], ["household_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_people_household_id"), "people", ["household_id"], unique=False)
    op.create_table(
        "task_dependencies",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("depends_on_task_id", sa.Uuid(), nullable=False),
        sa.Column("dependency_type", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["depends_on_task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "depends_on_task_id", name="uq_task_dependency_edge"),
    )
    op.create_index(
        op.f("ix_task_dependencies_depends_on_task_id"),
        "task_dependencies",
        ["depends_on_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_dependencies_task_id"), "task_dependencies", ["task_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_dependencies_task_id"), table_name="task_dependencies")
    op.drop_index(op.f("ix_task_dependencies_depends_on_task_id"), table_name="task_dependencies")
    op.drop_table("task_dependencies")
    op.drop_index(op.f("ix_people_household_id"), table_name="people")
    op.drop_table("people")
    op.drop_index(op.f("ix_external_applications_task_id"), table_name="external_applications")
    op.drop_index(op.f("ix_external_applications_status"), table_name="external_applications")
    op.drop_index(
        op.f("ix_external_applications_external_reference_id"), table_name="external_applications"
    )
    op.drop_table("external_applications")
    op.drop_index(op.f("ix_documents_verification_status"), table_name="documents")
    op.drop_index(op.f("ix_documents_produced_by_task_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_document_type"), table_name="documents")
    op.drop_index(op.f("ix_documents_case_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_audit_entries_task_id"), table_name="audit_entries")
    op.drop_index(op.f("ix_audit_entries_event_type"), table_name="audit_entries")
    op.drop_index(op.f("ix_audit_entries_case_id"), table_name="audit_entries")
    op.drop_table("audit_entries")
    op.drop_index(op.f("ix_approval_requests_task_id"), table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_status"), table_name="approval_requests")
    op.drop_table("approval_requests")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index("ix_tasks_case_id_status", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_life_events_case_id"), table_name="life_events")
    op.drop_table("life_events")
    op.drop_index(op.f("ix_household_profiles_case_id"), table_name="household_profiles")
    op.drop_table("household_profiles")
    op.drop_index(op.f("ix_cases_status"), table_name="cases")
    op.drop_table("cases")
    # ### end Alembic commands ###
